# 1.

In [2]:
X=input()
n=len(X)
i=0
j=n-1
def minDeletions(X, i, j):
    if i >= j:
        return 0
    if X[i] == X[j]:
        return minDeletions(X, i + 1, j - 1)

    return 1 + min(minDeletions(X, i, j - 1), minDeletions(X, i + 1, j))


print("The minimum number of deletions required are", minDeletions(X, 0, n - 1))


ABABABAC
The minimum number of deletions required are 1


# 2.

In [2]:
l=list(map(int,input().split()))
l.sort()
l

1 0 0 1 1 1 0 0 0


[0, 0, 0, 0, 0, 1, 1, 1, 1]

# 3.

In [13]:
l=list(map(int,input().split()))
arr=[]
for i in range(1,max(l)):
    if i not in l:
        arr.append(i)
    else:
        pass
print("Missing elements of array: ",arr)
print("smallest element: ",arr[0])

23 5 2 4 22 6
Missing elements of array:  [1, 3, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
smallest element:  1


# 4.

In [42]:
s=input()
l=[int(i) for i in s]
for i in range(len(l)-1,0,-1):
    if l[i]>l[i-1]:
        l[i-1],l[-1]=l[-1],l[i-1]
        break        
l=l[:i]+sorted(l[i:])
print(''.join((map(str,l))))

218765
251678


# 5.

In [69]:
import math
l=list(map(int,input().split()))
def isperfectSquare(l):
    s=int(math.sqrt(l))
    return s*s==l
arr=[]
for i in l:
    if isperfectSquare(i):
        arr.append(i)
    
if isperfectSquare(5*sum(arr)*sum(arr) + 4) or isperfectSquare(5*sum(arr)*sum(arr) - 4) :
    print("Sum is also a Fibonacci number")
else:
    print("Sum isn't a Fibonacci number")

4 6
Sum isn't a Fibonacci number


# 6.

In [112]:
l=list(map(int,input().split()))
a=l.copy()
pos=int(input())
a.sort()
if (l[pos:]+l[:pos])==a:
    print("array is sorted and rotated")
else:
    print("not rotated sorted array")

3 4 5 1 2
-2
array is sorted and rotated


# 7.

In [1]:
#Ackermann Function
def A(m, n, s ="% s"): 
    print(s % ("A(% d, % d)" % (m, n))) 
    if m == 0: 
        return n + 1
    if n == 0: 
        return A(m - 1, 1, s) 
    n2 = A(m, n - 1, s % ("A(% d, %% s)" % (m - 1))) 
    return A(m - 1, n2, s) 
  
print(A(int(input()), int(input()))) 
  

2
3
A( 2,  3)
A( 1, A( 2,  2))
A( 1, A( 1, A( 2,  1)))
A( 1, A( 1, A( 1, A( 2,  0))))
A( 1, A( 1, A( 1, A( 1,  1))))
A( 1, A( 1, A( 1, A( 0, A( 1,  0)))))
A( 1, A( 1, A( 1, A( 0, A( 0,  1)))))
A( 1, A( 1, A( 1, A( 0,  2))))
A( 1, A( 1, A( 1,  3)))
A( 1, A( 1, A( 0, A( 1,  2))))
A( 1, A( 1, A( 0, A( 0, A( 1,  1)))))
A( 1, A( 1, A( 0, A( 0, A( 0, A( 1,  0))))))
A( 1, A( 1, A( 0, A( 0, A( 0, A( 0,  1))))))
A( 1, A( 1, A( 0, A( 0, A( 0,  2)))))
A( 1, A( 1, A( 0, A( 0,  3))))
A( 1, A( 1, A( 0,  4)))
A( 1, A( 1,  5))
A( 1, A( 0, A( 1,  4)))
A( 1, A( 0, A( 0, A( 1,  3))))
A( 1, A( 0, A( 0, A( 0, A( 1,  2)))))
A( 1, A( 0, A( 0, A( 0, A( 0, A( 1,  1))))))
A( 1, A( 0, A( 0, A( 0, A( 0, A( 0, A( 1,  0)))))))
A( 1, A( 0, A( 0, A( 0, A( 0, A( 0, A( 0,  1)))))))
A( 1, A( 0, A( 0, A( 0, A( 0, A( 0,  2))))))
A( 1, A( 0, A( 0, A( 0, A( 0,  3)))))
A( 1, A( 0, A( 0, A( 0,  4))))
A( 1, A( 0, A( 0,  5)))
A( 1, A( 0,  6))
A( 1,  7)
A( 0, A( 1,  6))
A( 0, A( 0, A( 1,  5)))
A( 0, A( 0, A( 0, A( 1,  4))))
A( 0

# 8.

In [195]:
import numpy as np
def spiral(n,m,arr):
    k=l=0
    while(k<m and l<n):
        for i in range(l,n):
            print(arr[k][i],end=" ")
        k+=1 # k is now 1
        for i in range(k,m):
            print(arr[i][n-1],end=" ")
        n-=1
        if k<m:
            for i in range(n-1,l-1,-1):
                print(arr[m-1][i],end=" ")
            m-=1
        if l<n:
            for i in range(m-1,k-1,-1):
                print(arr[i][l],end=" ")
            l+=1
m=int(input())       
n=int(input())
arr=[]
for i in range(m):
    arr.append(list(map(int,input().split())))

l=np.array(arr)
l1=np.array(l.transpose())
print("transpose of array:-\n",l1)
spiral(m,n,l1)

4
6
1 2 3 4 5 6
1 1 1 2 2 2 
3 3 4 5 6 7
2 3 35 6 7 7
transpose of array:-
 [[ 1  1  3  2]
 [ 2  1  3  3]
 [ 3  1  4 35]
 [ 4  2  5  6]
 [ 5  2  6  7]
 [ 6  2  7  7]]
1 1 3 2 3 35 6 7 7 7 2 6 5 4 3 2 1 3 4 5 6 2 2 1 

# 9.

In [114]:
l=list(map(int,input().split()))
k=int(input())
if k<len(l):
    print(sorted(l)[k-1])

1 7 2 3 8 6 0 4
2
1


# 10.

In [118]:
k=int(input())
l=[]
for i in range(k):
    l1=list(map(int,input(f'enter the values for list {i+1}: ').split()))
    l1.sort()
    l=l+l1
l.sort()
print(l)

2
enter the values for list 1: 2 3 4 1 0
enter the values for list 2: 6 7 3 0 1 2
[0, 0, 1, 1, 2, 2, 3, 3, 4, 6, 7]


# 11.

In [120]:
N=int(input())
A=list(map(int,input().split()))
A.sort()
if len(A)>=3:
    print(A[-1]*A[-2]*A[-3])

7
0 7 1 2 3 46 3
966


# 12.

In [131]:
A=list(map(str,input().split()))
s=""
for i in range(min(len(A[0]),len(A[1]))):
    if A[0][i]==A[1][i]:
        s+=A[0][i]
print(s)

abcdefg abcefg
abc


# 13.

In [132]:
from itertools import combinations
arr=list(map(str,input().split()))
a1=map(float,arr)
a2=combinations(a1,3)
for a,b,c in a2:
    if a+b+c<2 and a+b+c>1:
        print(a,b,c)

0.2 1.2 8 7 6 1.9 0.22
0.2 1.2 0.22


# 14.

In [159]:
n=int(input())
arr=[]
for i in range(n):
    arr.append(list(map(int,input().split())))
result=[[0 for i in range(n)]for j in range(n)]
for i in range(n):
    k=0
    for j in range(n-1,-1,-1):
        result[i][k]=arr[j][i]
        k+=1
print("After rotating 90 degree clockwise:-\n")
for r in result:
    print(r)

2
2 3
4 5
After rotating 90 degree clockwise:-

[4, 2]
[5, 3]


# 15.

In [174]:
N=int(input())
arr=list(map(int,input().split()))
r=0
for i in range(1,N-2):
    m1,m2=max(arr[:i]),min(arr[i+1:])
    if arr[i]>m1 and arr[i]<m2:
        print(f'element {arr[i]} found at index {i} follows the condition')
        r=1
if r==0:
    print("there is no such element in array")

9
5 1 4 3 6 8 10 7 9
element 6 found at index 4 follows the condition
